### ISSUE TITLE
Improve tech organization

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#463]
There are a lot of techs, which leads to a lot of clutter to anyone trying to use them to customize item placement logic.

Things to consider:
- Can we remove any of the techs?
  - [x] `canHerdBabyTurtles` and its associated strat are so niche that maybe there's no value there. Resolved by #471
  - [x] `canMachball` is an alias and we don't use it. Maybe we can mention it in `canMockball`'s description and remove it? Resolved by #465
  - [x] `canSuitlessLavaWalljump` doesn't seem to bring anything that `canSuitlessLavaDive` + `canWalljump` doesn't. Resolved by #471
  - [x] `canPlasmaHitbox` seems more like a helper than a tech. Can't it just be `h_plasmaHitbox` and require `canHitbox` and `Plasma`? Resolved by #471
  - [x] `canIframeSpikeWalljump` probably doesn't bring much additional value vs. `canIframeSpikeJump` + `canWalljump`? Resolved by #471
  - [x] `canSunkenDualWallClimb` current requires hjb. We might want to remove that but replace current applications by a helper that has an OR (requiring either hjb or a modifier tech alongside it).
  - [x] `canQuickLowTideWalljumpWaterEscape` sounds like something that could be replaced by its current requirements + a modifier tech
  - [x] `canReverseGateGlitch` is used only one place: `Pink Brin Reverse GGG`. It feels like its other requirement of `canSuperReacharound` already covers the requirements appropriately, and that it's just an additional tech that's specific to a strat. Resolved by #471
  - [x] `canGTCode`, `canSpaceTime`, `canXRayClimbOOB` are not used anywhere. Maybe we could remove them until they're used. Resolved by #471
  - [ ] `canQuickCrumbleEscape` seems like it should be a combination of `canCrumbleQuickDrop` and some modifier tech. However, we don't have `canCrumbleQuickDrop` now so that wouldn't remove a tech.
- [x] Should we make extension techs easy to decipher in `tech.json` to help a UI display them in a hierarchical manner? Resolved by #473
- [x] Can we group techs together into categories? Resolved by #476 
- [x] Maybe we could try to order techs loosely by difficulty? Kinda done by #473  and #476
- [ ] Can we introduce some "modifier" techs that could be combined with other techs to reduce the overall number?  (Caveat: those are not really techs at all (and `canBePatient` is already in the same style). Maybe there can be a different solution instead, like strat descriptors or something)
  - Here's some example of modifier techs:
    - `canRiskExecutionSoftlock`
      - Counterpoint: Maybe it's better to tie this to the concept of strat `failures`. Someone could configure an expected number of tries to techs and strats, and consider that more than 1 expected try means dealing with the consequences
    - `canPreciseInputs`
    - `canPixelFramePerfectInputs`
    - `canPlayInSand`
  - Then we have a bunch of techs that could be replaced by combinations:
    - `canMorphlessTunnelCrawl` = `canTunnelCrawl` + `canRiskExecutionSoftlock`
    - `canSandMochtroidClimb` = `canMochtroidClimb` + `canRiskExecutionSoftlock` + `canPlayInSand`
    - `canSandIBJ` = `canIBJ` + `canPlayInSand`
    - `canTrickyJump` = `canPreciseInputs`
    - `canTrickyUseFrozenEnemies` = `canUseFrozenEnemies` + `canPreciseInputs`
    - `canPreciseWalljump` = `canWalljump` + `canPreciseInputs`
    - `canInsaneWalljump` = `canDelayedWallump` + `canPixelFramePerfectInputs`
    - `canPixelPerfectIceClip` = `canCeilingClip` + `canUseFrozenEnemies` + `canPixelFramePerfectInputs`. Consider replacing the combo by a helper.
    - `canNonTrivialIceClip` = `canCeilingClip` + `canUseFrozenEnemies` + `canPreciseInputs` + ( `canPixelFramePerfectInputs` OR `canXRayStandUp`). Consider replacing the combo by a helper.
    - Currently `canCWJ` inherently requires `canTrickyJump`. Should this be replaced by `canPixelFramePerfectInputs` rather than `canPreciseInputs`? The reason it isn't is probably just cause the moat CWJ is practiced so much. Maybe it should be pixel/frame perfect and if someone wants to put CWJ in logic they should override that notable strat to enabled.
    - NOTE: Some techs sound like they could be replaced like this, but involve inherently different knowledge or executions:
      - `canTrickyDashJump`. The quirks in jump height using SpeedBooster without hjb means this can be seen as its own tech and not just "A jump, but more precise".
      - `canWallIceClip`. Clipping into walls using a stream of spawner bugs is so different from anything else. It doesn't have a general tech like `canCeilingClip` to fall back onto.
- Are there techs that are redundant and can be better represented via helpers?
  - [x] e.g. `canGateGlitch`, `canGGG`, `canHeatedGateGlitch` and `canHeatedGGG` are all the same execution, just with varying resource costs. Resolved by #465
- [x] There has been feedback about `canStationaryMidAirMockball` (and `canMidAirMockball`): The tech name is confusing. Additionally, it can be argued it's not really a mockball, though the inputs are very similar but in different contexts. Maybe they could be changed to `canLateralMidAirMorph` and `canStationaryLateralMidAirMorph`? Resolved by #472 
- [x] The ice clip techs don't mention that they're ice clips, they could be renamed. Resolved by #472 
- [x] `canDraygonGrappleJump` has many issues:
  - [x] Name isn't as clear as it could be. `canDraygonTurretGrappleJump` would be better. Resolved by #475 
  - [x] It also doesn't have any electricity frames requirement right now.  Resolved by #495
  - [x] Also, maybe it could be removed altogether and just be a helper combining grapple jump, electricity frames, and a modifier tech. 
- [x] Should `canDownGrab` be made separate from `canCrouchJump`? They're different techs frequently used together. Maybe we could have a helper for the combination. Resolved by #465

Note that changing the structure of `tech.json` to present a hierarchy, or to put techs into groups, should be seen as a breaking change.

**Comment by kjbranch** [comment]
This issue could potentially be closed. There are two things left that could be discussed.
- Adding `canCrumbleQuickDrop` and using it in `canQuickCrumbleEscape`. 
- Introducing some "modifier" techs that could be combined with other techs to reduce the overall number?

The first one could have uses - I think there were some tight shinespark uses that could use this tech in Etecoon E-Tank Room.
I was more interested in the second one six months ago. I think I would rather not add the modifier tech now, but would be fine either way.

**Comment by osse101** [comment]
quickCrumbleEscape really sounds more like an application of a tech than canCrumbleQuickDrop so it is a change I'd like to make.     (also QuickCrumbleEscape would be similar to MM multiviola ice clip which doesn't have a quick drop)
Quick drops don't have many logical uses, but it does imply you are stuck under the crumble if you don't get the quickDrop.  So the natural difficulty of the tech is higher than a normal quickDrop for speed.

I am still interested in `Tags` used by the randomizer to filter techs, but that would be a different thing.  

There is already some modifier tech usage, most commonly with `canTrickyJump`.  Combining techs if working pretty well how we have it.  There is still a problem with assuming skill level for techs, like at which point and how well you can `short hop`.  And knowing enemy behaviours and stat tables.  And for analog things like that you could want to add a `East/Medium/Hard/VH` modifier to place it properly but we really want to avoid that kind of modifier.  But still, coming up with reasons to attach a difficult tech to place a strat is what we do sometimes.

I don't think that modifier techs to reduce tech count applies to how techs are written right now.  I'd rather keep adding more techs too. carefulJump and trickyJump maybe are overused and maybe there's a way to split them into more techs.

**Comment by kjbranch** [comment]
It looks like everything here is resolved apart from discussion on a single tech rename / slight change in use. There was also minimal discussion on `Tags`, but that has been moved to #1001. I'm closing this and opening a new issue about `canQuickCrumbleEscape`.
